Added Northern Ireland geography and area selection AND corresponding jitter plots
britishredcrosssociety/health-inequalities-explorer pull request #42
Opened 2023-07-18 15:17 UTC by MatteoLarrode

Hey Mike, as stated in the title of the PR, I made both geographies of Northern Ireland available to the user of the HIE. 

I also made changes to jitterPlot.R to enable the creation of the Northern Ireland jitter plots. 

You will notice that I did not add `northern_ireland_ltla_shp` and `northern_ireland_hsct_shp` to data/. 
That is because Niuni will do it, along with adding the mapping of Northern Ireland to the HIE.

2023-07-25 14:54 UTC, MikeJohnPage requested changes
As part of this pull request please can we add the relevant indicator descriptions in `R/indicatorDescriptions.R` to tie everything together nicely?

2023-07-25 14:54 UTC, MikeJohnPage commented on R/jitterPlot.R
> +      }else if (selected$geography == "northern_ireland_hsct_shp") {
Please style the file with `styler` to add the appropriate space.

2023-07-25 14:55 UTC, MikeJohnPage commented
Everything else looks great.

2023-07-26 16:53 UTC, MatteoLarrode commented
I had forgotten about indicator descriptions! I added them now. I kept the same structure as that of the other nations, but made sure to include the links Niuni and I used for the data.

2023-07-26 16:54 UTC, MatteoLarrode commented
I also fixed some typos I found in the file, and styled it.

2023-07-27 10:34 UTC, MikeJohnPage commented
All looks good. Thanks, merging now 🚀

2023-07-27 10:34 UTC, merged