Update lba data
britishredcrosssociety/health-inequalities-explorer pull request #50
Opened 2023-07-27 11:08 UTC by MatteoLarrode

Updated England Summary metrics datasets with latest Left behind areas data from the CNI. 

**_Local Authorities Level_**
 
Our LSOA to LTLA lookup uses 2022 codes for LTLA's, whereas our LTLA codes to names (based on LTLA boundaries dataset) is based on 2021 codes. I haven't found any change between 2021 and 2022 codes and I didn't run into any problem merging datasets, but I did want to flag this out to you (line 53 of `england_ltla_summary_metrics.R`)

**_ICB Level_**

The CNI uses LSOA 2021 codes, and our LSOA to ICB lookup used 2011 LSOA's. I had to do a bit of merging gymnastics that is explained in the screenshot below. 

Should I add a LSOA 2021 to ICB 2022 lookup to the geographr backlog? 

![Screenshot 2023-07-27 at 11 51 01](https://github.com/britishredcrosssociety/health-inequalities-explorer/assets/101408528/a8470572-0128-44e4-88a0-25be903ff260)

2023-07-27 16:19 UTC, MikeJohnPage requested changes

2023-07-27 16:19 UTC, MikeJohnPage commented on data-raw/england-icb-summary-metrics.R
> +  left_join(lookup_lsoa11_lsoa21_ltla22) |>
Unfortunately, this approach isn't valid. I will leave a more detailed in comment at the end of the review.

2023-07-27 16:29 UTC, MikeJohnPage commented
I really like your lateral thinking approach to looking up 2021 LSOA codes to ICB's. Unfortunately, it isn't valid because it assumes 2011 LSOA's map to 2021 LSOA's in 1:1 relationship, which isn't true. In the lookup table you used, `lookup_lsoa11_lsoa21_ltla22`, there is a column called `change_code` which documents the relationship between the LSOA's:

```r
r$> lookup_lsoa11_lsoa21_ltla22
# A tibble: 35,795 × 7
   lsoa11_name     lsoa11_code change_code lsoa21_name     lsoa21_code ltla22_name ltla22_code
   <chr>           <chr>       <chr>       <chr>           <chr>       <chr>       <chr>      
 1 Hartlepool 009A E01011949   U           Hartlepool 009A E01011949   Hartlepool  E06000001  
 2 Hartlepool 008A E01011950   U           Hartlepool 008A E01011950   Hartlepool  E06000001  
 3 Hartlepool 007A E01011951   U           Hartlepool 007A E01011951   Hartlepool  E06000001  
 4 Hartlepool 002A E01011952   U           Hartlepool 002A E01011952   Hartlepool  E06000001  
 5 Hartlepool 002B E01011953   U           Hartlepool 002B E01011953   Hartlepool  E06000001  
 6 Hartlepool 001A E01011954   U           Hartlepool 001A E01011954   Hartlepool  E06000001  
 7 Hartlepool 003A E01011955   U           Hartlepool 003A E01011955   Hartlepool  E06000001  
 8 Hartlepool 003C E01011957   U           Hartlepool 003C E01011957   Hartlepool  E06000001  
 9 Hartlepool 014A E01011959   U           Hartlepool 014A E01011959   Hartlepool  E06000001  
10 Hartlepool 014B E01011960   U           Hartlepool 014B E01011960   Hartlepool  E06000001  
# ℹ 35,785 more rows
# ℹ Use `print(n = ...)` to see more rows
```

In the documentation for the data set you will see it says:

> Change code containing U (unchanged from 2011 to 2021), M (merged), S (split) and X (irregular and fragmented change)

This means a simple lookup can't be performed and a more complex strategy must be taken. I've provided a solution to this problem in `data-raw/england-icb-demographics.R` which can be seen here: https://github.com/britishredcrosssociety/health-inequalities-explorer/blob/main/data-raw/england-icb-demographics.R#L20

Try and work your way through this logic, and then apply it to `data-raw/england-icb-summary-metrics.R`.

Thanks as ever for the great work and submissions!

2023-08-01 14:25 UTC, MatteoLarrode commented
I designed the aggregation method as follows:

![Screenshot 2023-08-01 at 14 48 55](https://github.com/britishredcrosssociety/health-inequalities-explorer/assets/101408528/9feb8c31-c1eb-415c-bae3-12b9a5a3a745)


The bottom line of this method is to avoid missing out on a left-behind area, even if it means assuming that all 2011 LSOA's that were merged are left-behind if the corresponding 2021 LSOA is left-behind for example.

2023-08-07 17:07 UTC, closed without merging